// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wLUabMsNeZ89NRgMWCB4bs
// Component: 1adzh6DBxrw_-E
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_testing_1.module.css"; // plasmic-import: wLUabMsNeZ89NRgMWCB4bs/projectcss
import sty from "./PlasmicCompletedForecast.module.css"; // plasmic-import: 1adzh6DBxrw_-E/css

export const PlasmicCompletedForecast__VariantProps = new Array("variants");

export const PlasmicCompletedForecast__ArgProps = new Array("children");

function PlasmicCompletedForecast__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        {
          [sty.rootvariants_tableRow]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__nZ3DC, {
          [sty.freeBoxvariants_tableRow__nZ3DCwGTfQ]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Wednesday",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenvariants_tableRow]: hasVariant(
              variants,
              "variants",
              "tableRow"
            )
          })
        })}
      </div>

      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img, {
          [sty.imgvariants_tableRow]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        })}
        displayHeight={"64px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"64px"}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__kznDf, {
          [sty.freeBoxvariants_tableRow__kznDfwGTfQ]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ryy0,
            {
              [sty.textvariants_tableRow__ryy0WGTfQ]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"68°"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__fSvc2,
            {
              [sty.textvariants_tableRow__fSvc2WGTfQ]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"36°"}
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___7JU7J, {
          [sty.freeBoxvariants_tableRow___7JU7JwGTfQ]: hasVariant(
            variants,
            "variants",
            "tableRow"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___2Slf,
            {
              [sty.textvariants_tableRow___2SlfwGTfQ]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"Pollen"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__dyvRl,
            {
              [sty.textvariants_tableRow__dyvRLwGTfQ]: hasVariant(
                variants,
                "variants",
                "tableRow"
              )
            }
          )}
        >
          {"35"}
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCompletedForecast__ArgProps,
          internalVariantPropNames: PlasmicCompletedForecast__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCompletedForecast__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedForecast";
  } else {
    func.displayName = `PlasmicCompletedForecast.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedForecast = Object.assign(
  // Top-level PlasmicCompletedForecast renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicCompletedForecast
    internalVariantProps: PlasmicCompletedForecast__VariantProps,
    internalArgProps: PlasmicCompletedForecast__ArgProps
  }
);

export default PlasmicCompletedForecast;
/* prettier-ignore-end */
