// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wLUabMsNeZ89NRgMWCB4bs
// Component: IJh9jQxyVuhn8P
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_testing_1.module.css"; // plasmic-import: wLUabMsNeZ89NRgMWCB4bs/projectcss
import sty from "./PlasmicLandmarks.module.css"; // plasmic-import: IJh9jQxyVuhn8P/css
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: Ln2SB_kH6f9ih8/icon

export const PlasmicLandmarks__VariantProps = new Array("variants");

export const PlasmicLandmarks__ArgProps = new Array();

function PlasmicLandmarks__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.rootvariants_wide]: hasVariant(variants, "variants", "wide") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___7P9U,
          {
            [sty.textvariants_wide___7P9U7Qfe0]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          }
        )}
      >
        {"Landmarks"}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__bVuzJ, {
          [sty.freeBoxvariants_wide__bVuzJ7Qfe0]: hasVariant(
            variants,
            "variants",
            "wide"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__szHeq, {
            [sty.freeBoxvariants_wide__szHeq7Qfe0]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__tD5Ib
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hnwNj
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__raydU)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox__tsFie, {
            [sty.freeBoxvariants_wide__tsFie7Qfe0]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__jKhoa,
              {
                [sty.textvariants_wide__jKhoa7Qfe0]: hasVariant(
                  variants,
                  "variants",
                  "wide"
                )
              }
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lXxAh
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__cuu2Y)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox___3Eb7, {
            [sty.freeBoxvariants_wide___3Eb77Qfe0]: hasVariant(
              variants,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8GObF
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cRnOh
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__qBkNc)}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandmarks__ArgProps,
          internalVariantPropNames: PlasmicLandmarks__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandmarks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandmarks";
  } else {
    func.displayName = `PlasmicLandmarks.${nodeName}`;
  }
  return func;
}

export const PlasmicLandmarks = Object.assign(
  // Top-level PlasmicLandmarks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLandmarks
    internalVariantProps: PlasmicLandmarks__VariantProps,
    internalArgProps: PlasmicLandmarks__ArgProps
  }
);

export default PlasmicLandmarks;
/* prettier-ignore-end */
