// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wLUabMsNeZ89NRgMWCB4bs
// Component: BUzUWHM3lcgXL
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_testing_1.module.css"; // plasmic-import: wLUabMsNeZ89NRgMWCB4bs/projectcss
import sty from "./PlasmicCompletedProfileCard.module.css"; // plasmic-import: BUzUWHM3lcgXL/css
import image115Tacu8KGwoSqLt from "./images/image11.png"; // plasmic-import: 5tacu8kGwoSqLT/picture

export const PlasmicCompletedProfileCard__VariantProps = new Array();

export const PlasmicCompletedProfileCard__ArgProps = new Array(
  "name",
  "username",
  "profilePicture"
);

function PlasmicCompletedProfileCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___5Jhn3)}
            displayHeight={"50px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"50px"}
            src={{
              src: image115Tacu8KGwoSqLt,
              fullWidth: 150,
              fullHeight: 184,
              aspectRatio: undefined
            }}
          />
        ),

        value: args.profilePicture
      })}

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__gPVza)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__sss8D)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__kjpoM)}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Totoro",
              value: args.name,
              className: classNames(sty.slotTargetName)
            })}
          </p.Stack>
        </p.Stack>

        {p.renderPlasmicSlot({
          defaultContents: "@friendlyneighbor",
          value: args.username,
          className: classNames(sty.slotTargetUsername)
        })}
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCompletedProfileCard__ArgProps,
          internalVariantPropNames: PlasmicCompletedProfileCard__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCompletedProfileCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedProfileCard";
  } else {
    func.displayName = `PlasmicCompletedProfileCard.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedProfileCard = Object.assign(
  // Top-level PlasmicCompletedProfileCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCompletedProfileCard
    internalVariantProps: PlasmicCompletedProfileCard__VariantProps,
    internalArgProps: PlasmicCompletedProfileCard__ArgProps
  }
);

export default PlasmicCompletedProfileCard;
/* prettier-ignore-end */
